### ISSUE TITLE
BLE disabling after update.

### ISSUE THREAD

**Issue by Subivan1** [bwp91/homebridge-govee#394]
### After updating to the latest version of the release the "instal" window freezes and the whole of homebridge freezes. Only way out is to manually restart the raspberry Pi. Going back to earlier version is partially successful. Going back to 7.5.0 takes a long time to load and restart the service and  still has the same errors.
Bluetooth is disabled on multiple devices, aultimately all of homebridge hangs and needs a physical restart.
No error messages with 

### Details of your setup.
* Do you use (1) Homebridge UI-X v4.50.2

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Raspberry Pi 3
* Node v18.12.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I was originally on 7.5.0 then 7.5.1 now trying 7.6
There have been minor issues on each upgrade, error messages during the install process but overall things recovered and went well.
errr message in the install window when trying to down grade  to 7.5.0 are as follows.
'''
CMD: sudo -E -n npm install -g homebridge-govee@7.5.0

(##################) ⠏ reify:typescript: timing reifyNode:node_modules/homebridge-gove
> @abandonware/bluetooth-hci-socket@0.5.3-9 install
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-9/bluetooth_hci_socket-0.5.3-9-node-v108-linux-arm.tar.gz 
make: Entering directory '/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.odge-gove
(##################) ⠹ reify:typescript: timing reifyNode:node_modules/homebridge-gove

'''' screen freezes and after a period the pi is physically restarted. this normally then proceeds to load and work well with HomeKit. However, I have noticed more instances of homebred becoming non response but with no noticeable errors.
 This same error appears when upgrading to 7.6

* Which Govee devices do you have that are causing issues? Please include product models if applicable. All Bluetooth models for example h6179 h6127

### Please paste any relevant logs below.

No real errors in logs, only the following warning which slows the process then continues after disabling BLE. The BLE gives lights are shown in HomeKit but are "no Esponse" all others work as expected.
```
[19/12/2022, 17:59:48] [Govee] [BLE] disabling client as Cannot find module '../build/Release/bluetooth_hci_socket.node'
Require stack:
- /usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js
- /usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/index.jsRequire stack:.
[19/12/2022, 17:59:48] [Govee] [Shed Led] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"enabled"}.
[19/12/2022, 17:59:48] [Govee] [Shed Led] initialised with id [A9:34:D4:AD:FC:1B:95:54] [H618A].
[19/12/2022, 17:59:48] [Govee] [Bookcase led] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[19/12/2022, 17:59:48] [Govee] [Bookcase led] initialised with id [53:85:7C:A6:B0:9D:32:8D] [H618A].
[19/12/2022, 17:59:48] [Govee] [Mac backlight] will be visible but uncontrollable as BLE not available.
[19/12/2022, 17:59:48] [Govee] [Mac backlight] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.


```

**Comment by Apollon77** [comment]
In fact it seems that the raspi crashes on build of the module bluetooth-hci-socket .. so ideally check what happens whily this build happens. Maybe it is not enoight RAM available? maybe have a "top" session in parallel.

The error afterwards just means tha the modile is not built

**Comment by Subivan1** [comment]
"top" shows a memory use for the install of about 11 to 18% with the MiB Mem showing as 924.2 total with 24.4 free, then the system hangs and the terminal session freezes as well.
<img width="1249" alt="Screenshot 2022-12-21 at 12 14 39" src="https://user-images.githubusercontent.com/44292198/208902897-752b5b3d-ddfe-4dd3-9b92-da2fd565ad40.png">
screen shot taken just before freeze 
error message in the install window is
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-govee@7.6.0

(##################) ⠏ reify:typescript: timing reifyNode:node_modules/homebridge-gove
> @abandonware/bluetooth-hci-socket@0.5.3-9 install
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-9/bluetooth_hci_socket-0.5.3-9-node-v108-linux-arm.tar.gz 
make: Entering directory '/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.o
In file included from /home/pi/.cache/node-gyp/18.12.1/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/pi/.cache/node-gyp/18.12.1/include/node/node.h:976:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/18.12.1/include/node/node.h:1010:3: note: in expansion of macro ‘NODE_MODULE_X’
 NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/BluetoothHciSocket.cpp:740:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(binding, BluetoothHciSocket::Init);
 ^~~~~~~~~~~
(##################) ⠹ reify:typescript: timing reifyNode:node_modules/homebridge-gove

**Comment by Apollon77** [comment]
hm ... check your ram stats please ...

954 MB RAM, 849 used, so "cached and free" is 70MB ... this might not be enough to compile the code ... You run your system on the veeeeerry edge of free RAM ... the smallest "need RAM spike" will kill anything - or in your case a update -  brings you into swapping which, with an SD card, is near to a dead.

Ideally try to get stuff splited or get more RAM. As a workaround maybe shutdown running services and install the update then so that ,ore RAM is free ... after that start it again

**Comment by Subivan1** [comment]
Thanks for the help, I disabled a number of other plugins, dropped the used ram down and successfully installed the update. I knew I was running at about max RAM so I should have thought about that myself. 
now however I get 
[BLE] disabling client as btClient.on is not a function at new default (file:///usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:18:14).

but I can see that is the other BLE error #393  that has been raised and its waiting on a fix from abandonware.

So thanks again. Now all I need is to find a Raspberry pi 4 with 8gb ram for sale

**Comment by Apollon77** [comment]
Yes, we ar on it to solve #393 soon too
