### ISSUE TITLE
Child Bridge is ending unexpectedly - this.platform.updateAccessoryStatus is not a function

### ISSUE THREAD

**Issue by ekalp** [bwp91/homebridge-govee#1317]
### What issue do you have?

After updating the plugin from v11.24.0 to v11.27.0, I am seeing failures for the child bridge. If I revert back to v11.24.0 I no longer see the issue.

Based on my testing the change that may be causing my issues was introduced in v11.25.0 and I'm unable to upgrade past v11.24.0. I have had BLE disable in the plugin settings as well.

### How do you run Homebridge?

Homebridge UI

### Homebridge/HOOBS Version

v2.1.1

### Which platform do you run Homebridge on?

Docker

### Plugin Version

v11.27.0

### Which Govee devices do you have that are causing issues?

Unknown

### Relevant Logs

```shell
[7/14/2026, 5:00:31 PM] [Govee] Child bridge starting (pid 18914)...
[7/14/2026, 5:00:33 PM] Registering platform '@homebridge-plugins/homebridge-govee.Govee'
[7/14/2026, 5:00:33 PM] [Govee] Child bridge started successfully (plugin v11.27.0).
[7/14/2026, 5:00:33 PM] Loaded 10 cached accessories from cachedAccessories.0ECB3744347E.
[7/14/2026, 5:00:33 PM] [Govee] Initialising plugin v11.27.0 | System linux | Node v24.18.0 | HB v2.1.1 | HAPNodeJS v2.1.8...
[7/14/2026, 5:00:33 PM] [Govee] Config entry [openApiDisable] is unused and can be removed.
[7/14/2026, 5:00:33 PM] [Govee] Plugin initialised. Setting up accessories....
[7/14/2026, 5:00:33 PM] Homebridge v2.1.1 (HAP v2.1.8) (Govee) is running on port 48514.
[7/14/2026, 5:00:35 PM] [Govee] [LAN] client enabled and found 0 device(s).
[7/14/2026, 5:00:36 PM] [Govee] [OPENAPI] client enabled and found 11 device(s).
[7/14/2026, 5:00:36 PM] [Govee] [HTTP] client enabled and found 10 device(s).
[7/14/2026, 5:00:36 PM] [Govee] [AWS] client enabled.
[7/14/2026, 5:00:36 PM] [Govee] [BLE] client enabled.
[7/14/2026, 5:00:36 PM] [Govee] [New Freezer] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [New Freezer] initialised with id [REDACTED] [H5108].
[7/14/2026, 5:00:36 PM] [Govee] [Old Freezer] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Old Freezer] initialised with id [REDACTED] [H5108].
[7/14/2026, 5:00:36 PM] [Govee] [LED Strip Light M1 - 2] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[7/14/2026, 5:00:36 PM] [Govee] [LED Strip Light M1 - 2] initialised with id [REDACTED] [H61E1].
[7/14/2026, 5:00:36 PM] [Govee] [LED Strip Light M1 - 1] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[7/14/2026, 5:00:36 PM] [Govee] [LED Strip Light M1 - 1] initialised with id [REDACTED] [H61E1].
[7/14/2026, 5:00:36 PM] [Govee] [Network Rack] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Network Rack] initialised with id [REDACTED] [H5100].
[7/14/2026, 5:00:36 PM] [Govee] [Garage] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Garage] initialised with id [REDACTED] [H5100].
[7/14/2026, 5:00:36 PM] [Govee] [Crawl Space] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Crawl Space] initialised with id [REDACTED] [H5100].
[7/14/2026, 5:00:36 PM] [Govee] [Attic - Shop] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Attic - Shop] initialised with id [REDACTED] [H5100].
[7/14/2026, 5:00:36 PM] [Govee] [Attic - Garage] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Attic - Garage] initialised with id [REDACTED] [H5100].
[7/14/2026, 5:00:36 PM] [Govee] [Attic - Master Bedroom] initialising with options {"lowBattThreshold":20,"showExtraSwitch":false}.
[7/14/2026, 5:00:36 PM] [Govee] [Attic - Master Bedroom] initialised with id [REDACTED] [H5100].
[7/14/2026, 5:00:36 PM] [Govee] [BLE] enabling sync for thermo sensor devices.
TypeError: this.platform.updateAccessoryStatus is not a function
    at default.externalUpdate (file:///homebridge/node_modules/@homebridge-plugins/homebridge-govee/lib/device/sensor-thermo.js:69:21)
    at default.receiveDeviceUpdate (file:///homebridge/node_modules/@homebridge-plugins/homebridge-govee/lib/platform.js:1885:27)
    at file:///homebridge/node_modules/@homebridge-plugins/homebridge-govee/lib/platform.js:1813:14
    at Map.forEach (<anonymous>)
    at default.receiveUpdateOpenAPI (file:///homebridge/node_modules/@homebridge-plugins/homebridge-govee/lib/platform.js:1811:17)
    at default.requestUpdate (file:///homebridge/node_modules/@homebridge-plugins/homebridge-govee/lib/connection/openapi.js:286:19)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at default.goveeOpenApiSync (file:///homebridge/node_modules/@homebridge-plugins/homebridge-govee/lib/platform.js:1598:11)
[7/14/2026, 5:00:38 PM] [Govee] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[7/14/2026, 5:00:38 PM] [Govee] Child bridge will automatically restart in 30 seconds (restart attempt 3 of 4).
```

**Comment by ekalp** [comment]
Also wanted to add that I have seen this in the logs as well:

[Entryway Crown Lights] is not currently supported, do create a Github issue with the following info:
{"device":"10642221","deviceName":"Entryway Crown Lights","model":"SameModeGroup","openApiInfo":{"capabilities":[{"type":"devices.capabilities.on_off","instance":"powerSwitch","parameters":{"dataType":"ENUM","options":[{"name":"on","value":1},{"name":"off","value":0}]}}],"byInstance":{"powerSwitch":{"type":"devices.capabilities.on_off","instance":"powerSwitch","parameters":{"dataType":"ENUM","options":[{"name":"on","value":1},{"name":"off","value":0}]}}},"category":null,"image":null},"properties":{},"supportCmds":["turn"]}

**Comment by bwp91** [comment]
Thanks for the precise version bisecting — that made this quick to pin down, and you found a genuinely old bug.

The crash is a missing function: the thermo/leak sensor code calls a helper (`updateAccessoryStatus`) to record when Govee reports a sensor going online/offline — but that helper was accidentally removed from the plugin **back in 2023**, while the sensor code kept calling it. It never crashed before because the online-status change path was rarely reachable; a change in v11.25.0 to how sensor data is merged made it fire for your H5108s, and the moment one of them changed online state, the child bridge died.

Two fixes are now published in **v11.27.1-beta.1**:

1. The missing helper is restored, so online/offline changes are logged properly instead of crashing.
2. While looking at your log I also noticed the plugin was warning about your Govee app *device groups* (`SameModeGroup`) as if they were unsupported devices — those are now skipped like real groups should be.

Could you update to the beta (Homebridge UI → plugin → manage version, or `npm i -g @homebridge-plugins/homebridge-govee@beta`) and confirm the bridge stays up? This will go into the next full release once confirmed 🙂

**Comment by bwp91** [comment]
Quick follow-up: both fixes are now in the full release, **v11.27.1**, so you can skip the beta and update to that directly. Since the missing function was the definitive cause of the crash, I'll close this one off — but if the child bridge misbehaves again after updating, reopen and I'm on it. Thanks again for the version bisecting, it made this a fast fix.

**Comment by ekalp** [comment]
Looks good, thank you for the quick turn around!
